name: Run CASR

on:
  push:

jobs:
  run-casr:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 1af1e82f0e54ff1700abb0b6ffb780dc7349e9ca
  
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Build project with JDK 17 
      run: mvn clean install -DskipTests

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        
    - name: Install CASR using Cargo
      run: cargo install casr

    - name: Run CASR on the .JAR file(s) (macOS)
      if: runner.os == 'macOS'
      continue-on-error: true
      run: |  
        mkdir -p casr_reports
        set +e
        #!/bin/bash
        directory=$(pwd)
        
        jar_files=$(find "$directory" -type f -name "*.jar")
        for jar_file in $jar_files; 
        do
            sanitized_main_class=$(sanitize_filename "$main_class")
            command="gtimeout 2m java -jar $runjpf_jar +classpath=$jar_file $main_class" 
            $command > "./casr_reports/${sanitized_main_class}_casr_report.txt"
        done
        
    - name: Run CASR on the .JAR file(s) (Linux)
      if: runner.os == 'Linux'
      continue-on-error: true
      run: |   
        mkdir -p casr_reports
        set +e
        #!/bin/bash
        directory=$(pwd)
        
        jar_files=$(find "$directory" -type f -name "*.jar")
        for jar_file in $jar_files; 
        do
            sanitized_main_class=$(sanitize_filename "$main_class")
            command="timeout 2m java -jar $runjpf_jar +classpath=$jar_file $main_class" 
            $command > "./casr_reports/${sanitized_main_class}_casr_report.txt"
        done
        
    - name: Upload CASR reports
      uses: actions/upload-artifact@v4
      with:
        name: casr-report-${{ github.event.repository.name}}-on-${{ matrix.os }}-from_branch_${{ github.ref_name }}
        path: './casr_reports/*'
